version: 2
jobs:
  build:
    docker:
    - image: mcr.microsoft.com/dotnet/core/aspnet:2.2
   # - image: circleci/postgres:9.6-alpine
      environment:
        DATABASE_URL: postgresql://postgres:pass@localhost/magic
        POSTGRES_USER: postgresuntu
        POSTGRES_DB: magic
        POSTGRES_PASSWORD: "pass"

    steps:
      - checkout
      - run:
        name: Install PostgreSQL Client
        command: |

        echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list

        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

        apt-get update

        apt-get install postgresql-client-9.6
      - run: |
          psql \
          -d $DATABASE_URL \
          -c "CREATE TABLE test (name char(25));"
      - run: |
          psql \
          -d $DATABASE_URL \
          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
      - run: |
          psql \
          -d $DATABASE_URL \
          -c "SELECT * from test"
      - run: echo "Testing"