version: 2
jobs:
  build:
    docker:
    - image: lostntkd/magicimage
      auth:
        username: lostntkd
        password: $DockerhubPassword
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: magic

    steps:
      - checkout
      - run:
          name: Start server
          command: service postgresql start
      - run:
          name: Configure Database
          command: python Backend/Database/DatabaseInstaller.py
      - run:
          name: Check directory
          command: ls
      - run:
          name: Run tests
          command: dotnet test