version: 2
jobs:
  build:
    docker:
    #- image: mcr.microsoft.com/dotnet/core/aspnet:2.2
    - image: circleci/postgres:9.6-alpine
      environment:
        DATABASE_URL: postgresql://postgres:pass@localhost/magic
        POSTGRES_USER: postgres
        POSTGRES_DB: magic
        POSTGRES_PASSWORD: "pass"

    steps:
      - checkout
      - run:
          name: Start server
          command: |
            service postgresql start
      - run: 
          name: Create test table
          command: |
            psql \
            -d $DATABASE_URL \
            -c "CREATE TABLE test (name char(25));"
      - run: 
          name: Create test table
          command: |
            psql \
            -d $DATABASE_URL \
            -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
      - run: 
          name: Create test table
          command: |
            psql \
            -d $DATABASE_URL \
            -c "SELECT * from test"
      - run: echo "Testing"