version: 2
jobs:
  build:
    docker:
      environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: mcr.microsoft.com/dotnet/core/aspnet:2.2
      - image: circleci/postgres:9.6.2-alpine
    steps:
      - checkout
      - run: echo "Testing"