version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/aspnet:2.2
      - image: circleci/postgres:9.6.2-alpine
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: echo "Testing"