version: 2.1
jobs:
  build:
    branches:
      only:
        - C#-conversions
    docker:
    - image: lostntkd/magicimage
      auth:
        username: lostntkd
        password: $DockerhubPassword

    steps:
      - checkout
      - run:
          name: Start server
          command: service postgresql start
      - run:
          name: Configure Database
          command: python Backend/Database/DatabaseInstaller.py
      - run:
          name: Check Dotnet version
          command: dotnet --version
      - run:
          name: Build project
          command: dotnet build -v d
  test:
    steps:
      - run:
          name: Run tests
          command: dotnet test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
