version: 2
jobs:
  build:
    docker:
    - image: lostntkd/magicimage
      auth:
        username: lostntkd
        password: DockerhubPassword

    steps:
      - checkout
      - run:
          name: Start server
          command: |
            service postgresql start
      - run:
          name: Login to postgres user
          command: su - postgres
      - run: 
          name: Create test table
          command: |
            psql \
            -d $DATABASE_URL \
            -c "CREATE TABLE test (name char(25));"
      - run: 
          name: Create test table
          command: |
            psql \
            -d $DATABASE_URL \
            -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
      - run: 
          name: Create test table
          command: |
            psql \
            -d $DATABASE_URL \
            -c "SELECT * from test"
      - run: echo "Testing"