version: 2
jobs:
  build:
    docker:
    - image: mcr.microsoft.com/dotnet/core/aspnet:2.2
    - image: circleci/postgres:9.6.2-alpine
      environment:
        DATABASE_URL: postgresql://root@localhost/magic

    steps:
      - checkout
      - run: |
          psql \
          -d $DATABASE_URL \
          -c "CREATE TABLE test (name char(25));"
      - run: |
          psql \
          -d $DATABASE_URL \
          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
      - run: |
          psql \
          -d $DATABASE_URL \
          -c "SELECT * from test"
      - run: echo "Testing"