version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/aspnet:2.2
      - image: circleci/postgres:9.6.2-alpine
      environment:
        DATABASE_URL: postgres://postgres:password@localhost:5432/magic
    steps:
      - checkout
      - run: echo "Testing"