version: 2
jobs:
  build:
    docker:
    - image: mcr.microsoft.com/dotnet/core/aspnet:2.2
    - image: circleci/postgres:9.6.2-alpine
      environment:
        TEST_DATABASE_URL: postgresql://root@localhost/circle_test

    steps:
      - checkout
      - run: echo "Testing"